server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${APP_NAME:"account"}

  elasticsearch:
    uris: http://localhost:9200

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST_DB:localhost}:${PORT_DB:5432}/accounts
    username: ${USER_DB:postgres}
    password: ${USER_PASS:12345}

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    url: jdbc:postgresql://${HOST_DB:localhost}:${PORT_DB:5432}/accounts
    user: ${USER_DB:postgres}
    password: ${USER_PASS:12345}


management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logstash:
  host: ${LOGSTASH_HOST:localhost:4560}