spring:
  application:
    name: customer

server:
  port: ${SERVER_PORT:8181}

account:
  api:
    url: http://${API_HOST:localhost}:${API_PORT:9999}/api/v1/accounts/1/transactions

logstash:
  host: "${LOGSTASH_HOST:localhost:4560}"
 