version: '3.8'

services:

  api01:
    #image: rogerbu/account:latest
    hostname: api01
    build:
      context: ../account
      dockerfile: Dockerfile
    environment:
      HOST_DB: accounts-db
      PORT_DB: 5432
      USER_DB: postgres
      USER_PASS: 12345
      SERVER_PORT: 8080
      LOGSTASH_HOST: logstash:4560
    ports:
      - "8080:8080"
    networks:
      - my-net
    healthcheck:
      test: "curl --fail --silent 127.0.0.1:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s
    depends_on:
      accounts-db:
        condition: service_healthy

  accounts-db:
    image: postgres:16
    container_name: accounts-db
    environment:
      POSTGRES_DB: "accounts"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    networks:
      - my-net
    volumes:
      - accounts-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s

networks:
  my-net:
    driver: bridge

volumes:
  accounts-db-data:
