version: '3.9'

services:

  customer-app:
    profiles:
      - producer
    image: rogerbu/customer:latest
    hostname: customer
    build:
      context: ../customer
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8181
      API_HOST: nginx
      API_PORT: 9999
      LOGSTASH_HOST: logstash:4560
    ports:
      - "8181:8181"
    networks:
      - my-net

  api01: &account-app
    profiles:
      - consumer
    image: rogerbu/account:latest
    hostname: api01
    build:
      context: ../account
      dockerfile: Dockerfile
    environment:
      HOST_DB: accounts-db
      PORT_DB: 5432
      USER_DB: postgres
      USER_PASS: 12345
      SERVER_PORT: 8080
      LOGSTASH_HOST: logstash:4560
      APP_NAME: ACCOUNT
    ports:
      - "8080:8080"
    networks:
      - my-net
    healthcheck:
      test: "curl --fail --silent 127.0.0.1:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s
    depends_on:
      accounts-db:
        condition: service_healthy

  api02:
    profiles:
      - consumer
    <<: *account-app
    hostname: api02
    ports:
      - "8081:8080"

  api03:
    profiles:
      - consumer
    <<: *account-app
    hostname: api03
    ports:
      - "8082:8080"

  nginx:
    profiles:
      - consumer
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my-net
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
      api03:
        condition: service_healthy
    ports:
      - "9999:9999"
    restart: always
    healthcheck:
      test: [ "CMD", "service", "nginx", "status", "||", "exit", "1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s

  accounts-db:
    profiles:
      - consumer
    image: postgres:alpine
    container_name: accounts-db
    environment:
      POSTGRES_DB: "accounts"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    networks:
      - my-net
    volumes:
      - accounts-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 3s

networks:
  my-net:
    driver: bridge

volumes:
  accounts-db-data: