global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'spring_micrometer'
    scrape_interval: 3s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'nginx:9999' ]

  - job_name: postgres-exporter
    scrape_interval: 3s
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]